project:
  type: website
  resources: 
    - "robots.txt"
  output-dir: docs

website:
  title: "Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - background.qmd
      - progress.qmd
      - href: open_questions.qmd
        text: Open Questions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


