---
title: "Projective Estimator"
format: html
---

### The Setup

We observe $n$ realized vectors via a data matrix $\underline{\mathbf{X}}\in\!\mathbb R^{n\times d}$, and want to estimate the underlying shape matrix of some potentially lower-dimensional subset of the components: $\mathbf \Sigma^{(k)} \in \mathbb R^{k \times k}$.

Some examples of situations where this comes up include:

- **Investing**: Estimating the dependence structure for a portfolio of $k=50$ stocks that trade in a market of $d=6,500$ total securities.
- **Genomics**: Estimating pathway-level dependence across $k=100$ genes from genome-wide expression profiles across $d=20,000$ genes. 
- **Simulation**: Think in 1d to 2d case...

Rather than discard these additional ambient dimensions (as is typical), because the same subordinator acts on each realization across the whole ambient space, we can use them to project an approximately Gaussian $k$-vector and get a better estimate of $\mathbf \Sigma^{(k)}$ under the right conditions. 


### Theoretical Model

We will build up the theoretical setup that mirrors the real-world setup, starting with consistent covariance structure.

Let $\{\mathbf \Sigma^{(d)}\}$, $d \geq 1$ be a sequence of symmetric matrices having the properties that:

- The leading principal $k \times k$ submatrix of $\mathbf \Sigma^{(d)}$ equals $\mathbf \Sigma^{(k)}$ for all $k \leq d$. 
- For any $d$, $\mathbf \Sigma^{(d)} \in \mathbb R^{d \times d}$ is positive definite and its eigenvalues $\lambda_i$, $i=1, \dots, d$ are uniformly bounded so that there exist two constants $m, M >0$ independent of $d$ such that $m \leq \lambda_i \leq M$ for all $i$. Additionally, assume that the average eigenvalue (or normalized trace in a random matrix theory context) converges to a fixed constant: $\frac{1}{d}\text{tr}(\mathbf \Sigma^{(d)})\rightarrow \tau>0$ as $d \rightarrow \infty$.

Next let $\{Z_i\}_{i \geq 1}$ be an infinite sequence of independent standard normal random variables. For each $d \geq 1$, set $\mathbf Z^{(d)} := (Z_1, \dots, Z_d)$ and $\mathbf G^{(d)}=\mathbf L^{(d)}\mathbf Z^{(d)}$, where $\mathbf L^{(d)}$ is the Cholesky factor satisfying $\mathbf L^{(d)}\mathbf L^{(d)\top}=\mathbf \Sigma^{(d)}$ (here, the Cholesky decomposition is needed to guarantee that the 'square roots' also nest and coordinate mixing doesn't change with $d$). 

Then for any $d$, $\mathbf G^{(d)} \sim N(\mathbf 0, \mathbf\Sigma^{(d)})$, and $G^{(k)}_i = G^{(d)}_i$ for any $i \leq k \leq d$. With this construction, the family $\{\mathbf G^{(d)}\}$ lives on a common probability space, and the first $k$ coordinates are identical for all $k \leq d$.

Finally, we can write the symmetric $\alpha$-stable random vector $\mathbf X^{(d)}$ using the stochastic representation $\mathbf X^{(d)}= \sqrt{W}\mathbf G^{(d)}$, where $W \sim S_{\alpha/2}(\cos(\pi \alpha/4)^{(2/\alpha)},1, 0;1)$, a maximally skewed scalar random variable with support on the positive real numbers that is independent of $\mathbf G^{(d)}$.

Define the projection $\mathbf X:=(X_1^{(d)}, \dots, X_k^{(d)}) \in \mathbb R^k$ with $k \leq d$ as the first $k$ coordinates of $\mathbf X^{(d)}$. Then, as defined above for any $k$, the dispersion matrix of $\mathbf X$ is simply $\mathbf \Sigma^{(k)}$ independent of the ambient dimension $d$. 

Under this setup, each $\mathbf X$ is a random vector centered at the origin whose shape matrix is the covariance matrix of the latent Gaussian vector $\mathbf G$ (e.g. the characteristic function of $\mathbf X$ is $\mathbb E[\exp\{i\pmb \theta^\top \mathbf X\}]= \exp(-(\frac{1}{2}\pmb\theta^{\text T}\mathbf\Sigma^{(k)}\pmb\theta)^{\alpha/2})$ (Samorodnitsky and Taqqu, Proposition 2.5.2)). This (potentially) lower-dimensional matrix $\mathbf \Sigma^{(k)}$ is the quantity we're interested in estimating. 

Note that the scale parameter of the univeriate stable random variable $X_i$ is just $\mathbf \Sigma^{(k)}_{ii}$ in the parameterization above. In the more common 1- and 2- parameterizations for stable random variables that don't include the $\frac 1 2$ factor in the characteristic function above, there is a one-to-one correspondence between the scale parameter $\gamma_i$ of the univariate stable random variable $X_i$ and the standard deviation $\sigma_i$ of the corresponding latent Gaussian $G_i$: $\sigma = \sqrt 2 \gamma$. We use this adjustment in the estimation procedure to estimate the trace of the latent covariance matrix using observable stable realizations.

In the full ambient space, we observe $n$ such realized vectors via a data matrix $\underline{\mathbf{X}}^{(d)} \in \mathbb{R}^{n\times d}$ so that each row is one $d$-dimensional observation:

$$
\underline{\mathbf{X}}^{(d)}   \;=\;
\begin{pmatrix}
x^{(d)}_{1,1} & x^{(d)}_{1,2} & \cdots & x^{(d)}_{1,d}\\
x^{(d)}_{2,1} & x^{(d)}_{2,2} & \cdots & x^{(d)}_{2,d}\\
\vdots        & \vdots        & \ddots & \vdots\\
x^{(d)}_{n,1} & x^{(d)}_{n,2} & \cdots & x^{(d)}_{n,d}
\end{pmatrix}\!\in\!\mathbb R^{n\times d}
$$ {#eq-data-matrix}

In the stable model, the $n$ observations are assumed to be i.i.d. copies of $\mathbf X^{(d)}$, but this isn't actually required by the estimation procedure provided that the latent Gaussian components of the vectors are i.i.d. This enables more interesting models, including those with dynamic distributions or time-series correlation.

We are interested in estimating the shape matrix of $X$ for some $k \leq d$. In other words, our estimation dimension of interest may be smaller than the observed ambient dimension of our random vector. Without loss of generality, assume that the leading dimensions are the estimation dimensions.



This setup 

::: {.callout-note}
This  $\mathbf X = \sqrt{W}\mathbf G$ setup is a so-called [normal variance mixture](https://en.wikipedia.org/wiki/Normal_variance-mean_mixture). In the literature, $W$ may be referred to as a subordinator (stable distribution literature), or a texture or a 2nd-order modular variate (signal processing). The distribution of this random variable determines the distribution of $\mathbf X$. For example if $W$ is inverse-gamma distributed rather than stable, $\mathbf X$ has a multivariate t distribution. This estimation approach works for any normal variance-mean mixture.
:::


### Estimation Procedure and Relation to Existing Approaches

Estimation using the projective estimator is straightforward:

1) Estimate marginal scale parameters $\gamma_j^{\text{MLE}}$, $j = 1, \dots, d$ via maximum likelihood.  
2) Use these marginal estimates to estimate the average trace of the full ambient-dimensional latent covariance matrix: $\hat\tau :=\frac{1}{d}\widehat{\text{tr}(\mathbf \Sigma^{(d)})} = \frac{2}{d}\sum_{j=1}^d  {\gamma_j^{\text{MLE}}}^2$ (Note: the 2 prefactor comes from differences between standard parameterizations of a Gaussian vs. general stable random vector used in the STABLE software). 
3) The projective estimator is the average of rank-1 normalized covariance matrices rescaled by this scale estimate:
$$
\hat{\pmb \Sigma} = \frac{d\hat\tau}{n}\sum_{i=1}^n\frac{\mathbf X_{i,\cdot}\mathbf X_{i,\cdot}^\top }{\|\mathbf X_{i,\cdot}^{(d)} \|^2}
$$ {#eq-projective-estimator} 

Where $\mathbf X_{i,\cdot}^{(d)} \in \mathbb R^d$ is the column vector made up of the $i$-th row of $\underline{\mathbf{X}}^{(d)}$, the $i$-th observation of the data matrix, and $\mathbf X_{i,\cdot} \in \mathbb R^k$ is the $k$-dimensional projection of $\mathbf X_{i,\cdot}^{(d)}$ as described above.

It turns out that this estimator is a rescaled version of the Spatial-Sign Covariance Matrix (SSCM), which was introduced by [Locantore, et al. (1999)](https://link.springer.com/article/10.1007/BF02595862), and has been studied extensively in various settings (see [Chen & Wang (2025)](https://arxiv.org/abs/2502.10943) for a thorough review). The SSCM can also be viewed as a one-shot version of Tyler's M-Estimator, using the identity as its initial guess for the fixed-point formula. 

Tyler's M-Estimator is the maximum likelihood estimator for the Angular Central Gaussian distribution ([Frahm & Uwe, 2007](https://www.econstor.eu/handle/10419/26740)), which is the distribution of the normalized data: $\mathbf X^{(d)}/\|\mathbf X^{(d)}\|=\mathbf G^{(d)}/\|\mathbf G^{(d)}\| \sim \text{ACG}(\mathbf \Sigma^{(d)})$. In both cases, these estimators are scatter matrix estimators and do not recover the scale of the covariance matrix, which is not uniquely defined by the ACG distribution (details in [Tyler (1987)](https://www.jstor.org/stable/2336697)).

For elliptical distributions, the SCCM maintains the eigenvectors and ordering of the eigenvalues of the scatter matrix ([Dürre et al. (2016)](https://www.sciencedirect.com/science/article/pii/S0167715215304065)), but distorts spacings in a complicated way that depends on $d$.

Very recent work by Chen & Wang (2025) explores the spectral properties of the SSCM for a general setup. In particular, they show that the Marcenko-Pastur distribution holds as a limiting distribution for the eigenvalues of the SCCM under certain regularity conditions, including sufficiently well-behaved tails.

To my knowledge existing work has not addressed the recovery of the proper scaling via high-dimensional norm concentration, the applicability of this approach to infinite variance distributions (regularly varying with $\alpha < 2$), the higher ambient dimension setup, the superefficiency of this estimator for certain heavy tailed distributions, or the recovery of the latent Gaussian vector G almost surely. 

### Motivation

Since the SCCM shares eigenvectors with the sample covariance matrix of G, which are consistent estimators of the shape matrix's eigenvectors, one approach to recover the full covariance matrix is to correct the eigenvalue distortions and reconstruct an estimate of the full covariance matrix. This is the motivation behind the Rotated MLE approach (not discussed in detail here). 

The projective estimator has slightly different motivation; we want to leverage the fact that in the high-dimensional setting, for any fixed components $i,j$, $\sqrt{d\tau}(X_i/\|\mathbf X^{(d)}\|, X_j/\|\mathbf X^{(d)}\|) \overset{a.s.}{\rightarrow} (G_i, G_j)$ as $d \rightarrow \infty$ (details below), as a consequence of concetration of vector norms in high dimensions and the marginalization property of Gaussians (that is, the sub-vector $(G_i, G_j)$ is invariant to the ambient dimension of $G$). In other words, the distortion of the eigenvalues becomes linear asyptotically as $d \rightarrow \infty$.

This is how the projective estimator gets its name: the projective central limit theorem suggests that the lower-dimensional projection of an anisotropic distribution on the sphere $\mathbb S^{d-1}$ becomes Gaussian in the infinite-dimensional limit (subject to some regularity conditions).

### Theoretical Properties

Returning to the representation $\mathbf X^{(d)}= \sqrt{W}\mathbf G^{(d)}$, the normalized stable vector $\mathbf X^{(d)}$ is equal to the normalized version of the corresponding latent Gaussian vector $G$. Note that under our consistent construction of $\mathbf X^{(d)}$, we can't use the eigendecomposition, since this results in different random variables for fixed components as $d$ grows.

But we still have:

$$
\begin{aligned}
\frac{\mathbf X}{\|\mathbf X^{(d)} \|} = \frac{\sqrt W\mathbf G}{\|\sqrt W\mathbf G^{(d)} \|} = \frac{\sqrt W\mathbf G}{\sqrt W\|\mathbf G^{(d)}\|} = \frac{\mathbf G}{\|\mathbf G^{(d)}\|}
\end{aligned}
$$

Next, note that the normalized squared norm of $\mathbf G^{(d)}$ converges almost surely to the normalized trace of $\mathbf \Sigma^{(d)}$. 

::: {#lem-offdiagonals}

## Convergence of $\frac 1 d \|\mathbf G^{(d)}\|^2$

$$
\frac 1 d \|\mathbf G^{(d)}\|^2 \underset{d \rightarrow \infty}{\overset{a.s.}{\longrightarrow}} \tau
$$

**Proof:** 

Call $\mathbf L^{(d)\top} \mathbf L^{(d)}  := \mathbf B^{(d)}$.

$$
\begin{aligned}
\frac 1 d \|\mathbf G^{(d)}\|^2 &= \frac 1 d \|\mathbf L^{(d)} \mathbf Z^{(d)}\|^2 \\
&= \frac 1 d (\mathbf L^{(d)} \mathbf Z^{(d)})^\top (\mathbf L^{(d)} \mathbf Z^{(d)})\\
& = \frac 1 d \mathbf Z^{(d)\top}\mathbf L^{(d)\top} \mathbf L^{(d)} \mathbf Z^{(d)} \\
&= \frac 1 d \mathbf Z^{(d)\top}\mathbf B^{(d)} \mathbf Z^{(d)}
\end{aligned}
$$

So we have a Gaussian quadratic form. Note that $\mathbf B^{(d)}$ has the same eigenvalues as $\mathbf \Sigma^{(d)}$, so $\text{tr}(\mathbf B^{(d)})=\text{tr}(\mathbf \Sigma^{(d)})$. 

$$
\begin{aligned}
\mathbb E \frac 1 d\|\mathbf G^{(d)}\|^2 &= \frac 1 d\mathbb E \|\mathbf U^{(d)}\mathbf \Lambda^{(d)}\mathbf {Z'}^{(d)}\|^2 \\
&= \frac 1 d\mathbb E \|\mathbf \Lambda^{(d)}\mathbf {Z'}^{(d)}\|^2 \\
&= \frac 1 d\mathbb E\bigg[ \sum_{i=1}^d \lambda_i {{Z'}_i^{(d)}}^2 \bigg] \\
&= \frac 1 d\sum_{i=1}^d  \lambda_i\\
&= \frac 1 d \text{tr}(\mathbf \Sigma^{(d)}) \\
&= \tau
\end{aligned}
$$

We can use the Hanson-Wright bound:

$$
\begin{aligned}
\sum_{d=1}^\infty \mathbb P(\frac 1 d \mathbf Z^{(d)\top}\mathbf B^{(d)} \mathbf Z^{(d)} - \frac 1 d \mathbb E \|\mathbf G^{(d)}\|^2  |>\epsilon) 
&= \sum_{d=1}^\infty \mathbb P(\mathbf Z^{(d)\top}\mathbf B^{(d)} \mathbf Z^{(d)} - \mathbb E \|\mathbf G^{(d)}\|^2  |>d\epsilon)\\
&\leq \sum_{d=1}^\infty 2\exp\bigg(-c\min\bigg\{\frac{d^2\epsilon}{\|\mathbf B^{(d)}\|_F^2}, \frac{d\epsilon}{\|\mathbf B^{(d)}\|_{\text{op}}}\bigg\}\bigg) \\ &\leq \sum_{d=1}^\infty 2\exp\bigg(-c\min\bigg\{\frac{d^2\epsilon}{c_2d}, \frac{d\epsilon}{M}\bigg\}\bigg) \\
& < \infty
\end{aligned}
$$

Here, the step from matrix norms come from the fact that $\|\mathbf B^{(d)}\|_F^2 = \mathcal O(d)$, and $\|\mathbf B^{(d)}\|_{\text{op}}\leq M$.

By the Borel-Cantelli lemma, $\frac 1 d \|\mathbf G^{(d)}\|^2 \underset{d \rightarrow \infty}{\overset{a.s.}{\longrightarrow}} \tau\ \square$

:::

Taking square roots and applying the continuous mapping theorem, we get $\frac{1}{d}\|\mathbf G^{(d)}\|^2 \underset{d \rightarrow \infty}{\overset{\text{a.s.}}{\longrightarrow}} \tau \implies \frac{\|\mathbf G^{(d)}\|}{\sqrt {d \tau}}\underset{d \rightarrow \infty}{\overset{\text{a.s.}}{\longrightarrow}} 1$. 

This means that for any fixed indices $i,j$, we get:

$$
\begin{aligned}
\sqrt {d \tau} \frac{(X_i, X_j)}{\|\mathbf X^{(d)} \|} =\sqrt {d \tau}\frac{(G_i, G_j)}{\|\mathbf G^{(d)}\|}  \underset{d \rightarrow \infty}{\overset{\text{a.s.}}{\longrightarrow}} (G_i, G_j)
\end{aligned}
$$

By the continuous mapping theorem, the product $d\,\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}\underset{d \rightarrow \infty}{\overset{\text{a.s.}}{\longrightarrow}} G_iG_j$ as well.

Now, consider that for the latent Gaussian vector $\mathbf G$, we can write: 

$$
\mathbb E [\mathbf G \mathbf G^\top] = 
\begin{pmatrix}
\mathbb{E}[G_1^2] & \mathbb{E}[G_1G_2] & \cdots & \mathbb{E}[G_1G_k] \\
\mathbb{E}[G_2G_1] & \mathbb{E}[G_2^2] & \cdots & \mathbb{E}[G_2G_k] \\
\vdots & \vdots & \ddots & \vdots \\
\mathbb{E}[G_kG_1] & \mathbb{E}[G_kG_2] & \cdots & \mathbb{E}[G_k^2]
\end{pmatrix}
$$

So that we can recover $\mathbb E [\mathbf G \mathbf G^\top]  =\mathbf \Sigma^{(k)}$ elementwise without ever considering projections of more than two components of $\mathbf G$ at a time. While the size of the matrix $\mathbf \Sigma^{(k)}$ can be allowed to grow with $d$ if we wish, each entry is independent of the ambient dimension. 

::: {#lem-uniform-int}

## Uniform Integrability of Normalized Product Moments

$d\,\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}$ is uniformly integrable.

::: {.callout-note collapse="true"}
## Proof

First, it's known that $\bigg(\frac{{Z'}_i}{\|\mathbf {Z'}\|}\bigg)^2 \sim \text{Beta}\bigg(\frac 1 2, \frac{d-1}{2}\bigg)$. This is shown in a few places, but an elegant proof and additional textbook references can be found online [here](https://math.stackexchange.com/questions/1602036/marginal-distribution-of-uniform-vector-on-sphere).

So $\mathbb E\bigg[\bigg(\frac{{Z'}_i}{\|\mathbf {Z'}\|}\bigg)^4\bigg]=\frac{3}{d(d+2)} \implies \mathbb E\bigg[\bigg\{\bigg(\sqrt d \frac{{Z'}_i}{\|\mathbf {Z'}\|}\bigg)^2\bigg\}^2 \bigg]=\frac{3d}{(d+2)}\leq 3$ for all $d > 0$. Since $\bigg(\sqrt d \frac{{Z'}_i}{\|\mathbf {Z'}\|}\bigg)^2$ has a uniform $L^2$ bound, it is uniformly integrable.

Combining this with the assumptions that the eigenvalues of $\mathbf \Sigma^{(d)}$ are uniformly bounded and independent of $d$, with $\lambda_{\text{max}}(\mathbf \Sigma^{(d)}) \leq M$ and $\lambda_{\text{min}}(\mathbf \Sigma^{(d)}) \geq m$:

$$
\begin{aligned}
\bigg(\frac{\sqrt {d \tau} X_i}{\|\mathbf X^{(d)}\|}\bigg)^2 &= \frac{d \tau X_i^2}{\|\mathbf X^{(d)}\|^2} \\
&= \frac{d \tau (\sqrt W G_i)^2}{\|\sqrt W \mathbf G^{(d)}\|^2} \\ 
&= \frac{d \tau G_i^2}{\|\mathbf G^{(d)}\|^2} \\
& \leq  \frac{d \tau (\sqrt M{Z'}_i)^2}{\|\mathbf \Lambda^{1/2}\mathbf{Z'}^{(d)}\|^2} \\ 
& \leq \frac{d \tau (\sqrt MZ_i)^2}{(\sqrt m\|\mathbf {Z'}^{(d)}\|)^2} \\
&= \frac {\tau M}{m}\bigg(\sqrt d \frac{{Z'}_i}{\|\mathbf {Z'}^{(d)}\|}\bigg)^2
\end{aligned}
$$

That is a uniformly integrable random variable times a constant, which is also uniformly integrable.

Then for any fixed $i,j$, by the Cauchy-Schwarz inequality, we have: 

$$
\begin{aligned}
\bigg|d\,\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}\bigg| \leq \frac 1 2 \bigg ( \bigg(\frac{\sqrt {d \tau} X_i}{\|\mathbf X^{(d)}\|}\bigg)^2 + \bigg(\frac{\sqrt {d \tau} X_j}{\|\mathbf X^{(d)}\|}\bigg)^2\bigg)
\end{aligned}
$$

Because each squared term on the right-hand side is already uniformly integrable, the product $\bigg(d\,\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}\bigg)$ is bounded above by a uniformly integrable random variable, so it is also uniformly integrable, as desired. $\square$
:::

:::

By Lemma 2, uniform integrability and a.s. convergence of product described above means that the following interchange of limits and expectation is warranted by Vitali's convergence theorem:
$$
\lim_{d\to\infty} \mathbb{E}\!\left[d\,\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}\right] = \mathbb{E}\!\left[ \lim_{d\to\infty}d\tau\,\frac{X_i}{\|\mathbf X^{(d)} \|}\frac{X_j}{\|\mathbf X^{(d)} \|}\right] = \mathbb{E}[G_iG_j] = \Sigma_{ij}
$$

Since this quantity doesn't depend on $d$, this shows that
$$
d\,\tau\,\mathbb{E}\!\left[\frac{X}{\|\mathbf X^{(d)} \|}\frac{X}{\|\mathbf X^{(d)} \|}^\top\right] \to \mathbb{E}[GG^\top] = \Sigma^{(k)}
$$

in the sense that every finite block converges entrywise.

#### Efficiency 

In the Gaussian case, the Slepian-Bangs formula gives the (i,j)th element of the Fisher Information Matrix for the Gaussian as  $I_{ij} = n\cdot \text{tr}\{{\mathbf \Sigma}^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_i}{\mathbf \Sigma}^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_j}\}$. 

For the whole matrix, this yields $\mathbf I(\text{vec}(\mathbf {\Sigma^{(d)}}))=\frac{n}{2}(\mathbf {\Sigma^{(d)}}^{-1}\otimes \mathbf{\Sigma^{(d)}}^{-1})$, so that the CRB matrix is just $\mathbf I^{-1}=\text{CRB}(\mathbf {\Sigma^{(d)}})=\frac{2}{n}(\mathbf {\Sigma^{(d)}}\otimes \mathbf{\Sigma^{(d)}})$. 

With some lengthy manipulation, this leads to the familiar Cramér-Rao Bound (CRB) for the (i,j)th element of the inverse of this matrix: $\text{CRB}(\Sigma_{ij}) = \frac 1 n [\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2]$.

We assume that [DuMouchel's criteria](https://projecteuclid.org/journals/annals-of-statistics/volume-1/issue-5/On-the-Asymptotic-Normality-of-the-Maximum-Likelihood-Estimate-when/10.1214/aos/1176342516.full) for the asymptotic normality of stable MLEs are satisfied, and that $n$ is sufficiently large that the marginal scale estimators have finite variance. Beyond that, we don't rely on any limiting arguments about the sample size.

For any $i,j \leq k$:

$$
\begin{aligned}
\mathbb E(d\hat\tau G_iG_j) &= \mathbb E(d\hat\tau G_iG_j - d\tau G_iG_j +  d\tau G_iG_j ) \\
&= \mathbb E(d\tau G_iG_j + d(\hat\tau - \tau) G_iG_j) \\ 
&= d\tau\text{Cov}(G_i,G_j) + \mathbb E[d(\hat\tau - \tau) G_iG_j] \\
&\leq d\tau\Sigma_{ij} +\sqrt{\text{Var}(d\hat\tau)} \sqrt{\mathbb E[(G_iG_j)^2]} \\
&= d\tau\Sigma_{ij} + \sqrt{\mathcal O (d^{1-\beta})} \sqrt{\mathcal O(1)} \\
&= d\tau\Sigma_{ij} + \mathcal O (d^{(1-\beta)/2})
\end{aligned}
$$

Where $0 < \beta \leq 1$ is a term that depends on the correlation of the marginal MLEs (since $\tau$ is the average of finite variance random variables that cannot be perfectly correlated). So the bias term is $\mathcal O (d^{(1-\beta)/2})$ or smaller.

Using a Taylor series expansion for the expectation and variance of the ratio $\hat\Sigma_{ij} = d\hat\tau X_iX_j/\|X\|^2$ around $(\mathbb E(d\hat\tau G_iG_j), \mathbb E(\|G\|^2))=(d\tau\Sigma_{i,j}+ \mathcal O (d^{(1-\beta)/2}), d\tau)$, starting with the moments:

$$
\begin{aligned}
\mathbb E (d\hat\tau X_iX_j/\|X\|^2) =\mathbb E (d\hat\tau G_iG_j/\|G\|^2) &= \mathbb E [ d\hat\tau G_iG_j/\|G\|^2 +  d\tau G_iG_j/\|G\|^2 - d\tau G_iG_j/\|G\|^2] \\
&= \mathbb E [ d\tau G_iG_j/\|G\|^2] + \mathbb E [d(\hat\tau - \tau) G_iG_j/\|G\|^2] \\
&= \frac{\mathbb E(d\hat\tau G_iG_j)}{\mathbb E(\|G\|^2)}+\mathcal O (\frac{1}{d})+ \mathbb E [d(\hat\tau - \tau) G_iG_j/\|G\|^2] \\
&\leq \frac{\mathbb E(d\hat\tau G_iG_j)}{\mathbb E(\|G\|^2)}+\mathcal O (\frac{1}{d})+ \sqrt{\text{Var}(\hat\tau)}\sqrt{\mathbb E [(dG_iG_j/\|G\|^2)^2]}\\
&= \frac{\mathbb E(d\hat\tau G_iG_j)}{\mathbb E(\|G\|^2)}+\mathcal O (\frac{1}{d})+ \sqrt{\mathcal O (d^{-\beta})}\sqrt{\mathcal O(1)}\\
&= \frac{\mathbb E(d\hat\tau G_iG_j)}{\mathbb E(\|G\|^2)}+\mathcal O (\frac{1}{d^{\beta/2}}) \\
&= \frac{d\tau\Sigma_{i,j}+ \mathcal O (d^{(1-\beta)/2})}{d\tau} +\mathcal O (\frac{1}{d^{\beta/2}}) \\
&=  \frac{d\tau\Sigma_{i,j}}{d\tau} +  \frac{\mathcal O (d^{(1-\beta)/2})}{d\tau}+\mathcal O (\frac{1}{d^{\beta/2}}) \\
&= \Sigma_{ij}+\mathcal O (\frac{1}{d^{\beta/2}}) 
\end{aligned}
$$

Another building block:

$$
\begin{aligned}
\mathbb E [ (d\hat\tau G_iG_j/\|G\|^2)^2] &= \mathbb E [ (d\hat\tau G_iG_j/\|G\|^2 +  d\tau G_iG_j/\|G\|^2 - d\tau G_iG_j/\|G\|^2)^2] \\ 
&= \mathbb E \bigg[ \bigg(d\tau G_iG_j/\|G\|^2 +d(\hat\tau - \tau) G_iG_j/\|G\|^2\bigg)^2\bigg] \\
&=  \mathbb E \bigg[\bigg(\frac{d\tau G_iG_j}{\|G\|^2}\bigg)^2\bigg] + \mathbb E \bigg[\frac{2d^2\tau(\hat\tau - \tau)G_i^2G_j^2}{\|G\|^4} +\bigg(\frac{d(\hat\tau - \tau) G_iG_j}{\|G\|^2}\bigg)^2\bigg] \\
&= \bigg[\frac{d^2\tau^2\Sigma_{ij}^2}{d^2\tau^2} + \frac{d^2\tau^2\text{Var}(G_iG_j)}{d^2\tau^2}+ \mathcal O(\frac 1 d )\bigg] + \mathbb E \bigg[\frac{2d^2\tau(\hat\tau - \tau)G_i^2G_j^2}{\|G\|^4} +\bigg(\frac{d(\hat\tau - \tau) G_iG_j}{\|G\|^2}\bigg)^2\bigg] & (*) \\
&= \bigg[\Sigma_{ij}^2+ (\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2) + \mathcal O(\frac 1 d )\bigg] + \mathbb E \bigg[\frac{2d^2\tau(\hat\tau - \tau)G_i^2G_j^2}{\|G\|^4} +\bigg(\frac{d(\hat\tau - \tau) G_iG_j}{\|G\|^2}\bigg)^2\bigg] \\
&= \bigg[\Sigma_{ij}^2+ (\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2) + \mathcal O(\frac 1 d )\bigg] + \mathbb E \bigg[\frac{2d^2\tau(\hat\tau - \tau)G_i^2G_j^2}{\|G\|^4}\bigg] + \mathbb E \bigg[\bigg(\frac{d(\hat\tau - \tau) G_iG_j}{\|G\|^2}\bigg)^2\bigg] \\
&\leq \bigg[\Sigma_{ij}^2+ (\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2) + \mathcal O(\frac 1 d )\bigg] + \sqrt{\text{Var}(\hat\tau)}\sqrt{\mathbb E \frac{4d^4\tau G_i^4G_j^4}{\|G\|^8}} + \sqrt{\mathbb E(\hat\tau - \tau)^4}\sqrt{\mathbb E\frac{4d^4\tau^2 G_i^4G_j^4}{\|G\|^8}} & (**)\\
&= \bigg[\Sigma_{ij}^2+ (\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2) + \mathcal O(\frac 1 d )\bigg] +\sqrt{\mathcal O(\frac{1}{d^\beta})}\sqrt{\mathcal O(1)}+\sqrt{\mathcal O(\frac{1}{d^{2\beta}})}\sqrt{\mathcal O(1)}\\ 
&= 2\Sigma_{ij}^2+ \Sigma_{ii}\Sigma_{jj} + \mathcal O (\frac{1}{d^{\beta/2}}) 
\end{aligned}
$$

Above, (*) follows from another Taylor series expansion of the first bracketed term, and (**) comes from bounding the order of the expectations with respect to $d$ using the Cauchy-Schwartz inequality.

Putting these together for the general covariance of any arbitrary pair of estimates:

$$
\begin{aligned}
\text{Cov}(\hat\Sigma_{ij},\hat\Sigma_{kl}) &= \mathbb E[\hat\Sigma_{ij}\hat\Sigma_{kl}]-\mathbb E[\hat\Sigma_{ij}]\mathbb E[\hat\Sigma_{kl}] \\
&= \mathbb E\bigg[\frac{d\hat\tau X_iX_j}{\|\mathbf X^{(d)}\|^2}\frac{d\hat\tau X_kX_l}{\|\mathbf X^{(d)}\|^2}\bigg]-\mathbb E\bigg[\frac{d\hat\tau X_iX_j}{\|\mathbf X^{(d)}\|^2}\bigg]\mathbb E\bigg[\frac{d\hat\tau X_kX_l}{\|\mathbf X^{(d)}\|^2}\bigg] \\
&= \mathbb E\bigg[\frac{d^2\hat\tau^2 X_iX_jX_kX_l}{\|\mathbf X^{(d)}\|^4}\bigg] - (\Sigma_{ij} + \mathcal O(d^{-\beta/2}))(\Sigma_{kl} + \mathcal O(d^{-\beta/2}))\\
&= \mathbb E\bigg[\frac{d^2\hat\tau^2 G_iG_jG_kG_l}{\|\mathbf G^{(d)}\|^4}\bigg] - \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\
&= \mathbb E\bigg[\frac{G_iG_jG_kG_l}{\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4}\bigg] - \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\
&= \frac{\mathbb E[G_iG_jG_kG_l]}{\mathbb E [\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4]} - \frac{\text{Cov}(G_iG_jG_kG_l,\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])}{\mathbb E [\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4]^2}+ \frac{\text{Var}(\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])\mathbb E[G_iG_jG_kG_l]}{\mathbb E [\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4]^3}- \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\ 
&= \frac{\mathbb E[G_iG_jG_kG_l]}{1+\mathcal O(d^{-\beta/2})} - \frac{\text{Cov}(G_iG_jG_kG_l,\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])}{(1+\mathcal O(d^{-\beta/2}))^2}+\frac{\text{Var}(\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])\mathbb E[G_iG_jG_kG_l]}{(1+\mathcal O(d^{-\beta/2}))^3}- \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\
&= \mathbb E[G_iG_jG_kG_l] + \text{Cov}(G_iG_jG_kG_l,\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])+\text{Var}(\frac{1}{d^2\hat\tau^2}\|\mathbf G^{(d)}\|^4])\mathbb E[G_iG_jG_kG_l]- \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\
&= \Sigma_{ij}\Sigma_{kl} +\Sigma_{ik}\Sigma_{jl}+\Sigma_{il}\Sigma_{jk} + \mathcal O (d^{-1/2}) + \mathcal O (d^{-1}) +\mathcal O(d^{-\beta/2}) - \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2})\\
&= \Sigma_{ij}\Sigma_{kl} +\Sigma_{ik}\Sigma_{jl}+\Sigma_{il}\Sigma_{jk} - \Sigma_{ij}\Sigma_{kl} + \mathcal O(d^{-\beta/2}) \\
&= \Sigma_{ik}\Sigma_{jl}+\Sigma_{il}\Sigma_{jk} + \mathcal O(d^{-\beta/2}) 
\end{aligned}
$$

In the special case where $i=k, j=l$ we have the variance:
$$
\begin{aligned}
\text{Var}(d\hat\tau G_iG_j/\|G\|^2) &= \mathbb E \bigg[ (d\hat\tau G_iG_j/\|G\|^2)^2\bigg] - \mathbb E \bigg[d\hat\tau G_iG_j/\|G\|^2 \bigg]^2\\
& = \bigg[2\Sigma_{ij}^2+ \Sigma_{ii}\Sigma_{jj} + \mathcal O (\frac{1}{d^{\beta/2}})\bigg] - \bigg[\Sigma_{ij}+\mathcal O (\frac{1}{d^{\beta/2}})\bigg]^2  \\
&= \bigg[2\Sigma_{ij}^2+ \Sigma_{ii}\Sigma_{jj} + \mathcal O (\frac{1}{d^{\beta/2}})\bigg] - \bigg[\Sigma_{ij}^2+\mathcal O (\frac{1}{d^{\beta/2}})\bigg]\\
& = \Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2 + \mathcal O (\frac{1}{d^{\beta/2}})
\end{aligned}
$$

So, for fixed indices $i,j$, even if we fix the sample size $n$, the variance of our estimator achieves the Gaussian CRB plus a bias term that vanishes as $d$ increases. When we let $n$ grow, by the independence of the samples, both terms in the variance above scale by $\frac 1 n$.

More generally, this shows that the matrix whose entries are $\text{Cov}(\hat\Sigma_{ij},\hat\Sigma_{kl})$ matches the Gaussian CRB matrix entrywise in the limit as $d \rightarrow \infty$.

Choose estimation dimension $k = k(d) = \mathcal o(d^{\beta/4})$. Then, looking at the MSE of our estimator over the entire set of possible indices $i,j \leq k$ for any individual row of our estimation matrix $\textbf X_{[k]}$, and defining $\Omega$ as the CRLB matrix for $\Sigma^{(k)}$:

$$
\begin{aligned}
\mathbb E \|\hat \Sigma^{(k)} - \Sigma^{(k)}  \|_F^2 &= \mathbb E \bigg \| d\hat\tau \frac{X_{[k]} X_{[k]}^{\top}}{\|X\|^2} - \Sigma^{(k)}  \bigg\|_F^2 \\
&= \mathbb E \bigg \| d\hat\tau \frac{G_{[k]}G_{[k]}^{\top}}{\|G\|^2} - \Sigma^{(k)} \bigg\|_F^2 \\
&= \mathbb E \sum_{i,j} (d\hat\tau G_iG_j/\|G\|^2 - \Sigma_{ij})^2 \\
&= \sum_{i,j} \text{Var}(d\hat\tau G_iG_j/\|G\|^2)+ \sum_{i,j}(\Sigma_{ij} - \mathbb E\hat \Sigma_{ij})^2\\ 
&= \sum_{i,j} \text{Var}(d\hat\tau G_iG_j/\|G\|^2)+\sum_{i,j}\mathcal O (\frac{1}{ d^{\beta}}) \\
&= \sum_{i,j}\bigg[\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2 + \mathcal O(\frac{1}{d^{\beta/2} })\bigg] +\sum_{i,j}\mathcal O (\frac{1}{ d^{\beta}})  \\
&= \sum_{i,j}[\Sigma_{ii}\Sigma_{jj}+\Sigma_{ij}^2]+\mathcal O(\frac{k^2}{d^{\beta/2} }) \\
&= \text{tr}(\Omega) + \mathcal O(\frac{1}{d^{\beta/2} }) \\
\implies  \frac{\mathbb E \|\hat \Sigma - \Sigma \|_F^2}{\text{tr}(\Omega)} &= 1 + \mathcal O(\frac{1}{d^{\beta/2+1} }) \\ 
\end{aligned}
$$

So taking the limit as $d \rightarrow \infty$, our estimator saturates the Gaussian global lower MSE bound as long as we choose $k = k(d) = \mathcal o(d^{\beta/4})$ (e.g. $k$ can be allowed to go to infinity along with $d$, provided it grows no faster than $d^\frac{\beta}{4}$). 

With $n$ i.i.d. rows, the variance terms scale as $1/n$, so averaging over multiple observations shrinks the additive Frobenius error by a factor of $1/n$, but leaves the risk ratio above unchanged. 

#### Asymptotic Superefficiency

Because we saturate the Gaussian global lower MSE bound, this estimator is "superefficient" (with respect to the Frobenius norm metric above) under the right conditions. 

In the limit as $d \rightarrow \infty$, the projective achieves a lower global MSE than possible under the Cramér–Rao bound matrix for the original distribution. This doesn't contradict the usual Cramér–Rao theory, because our estimator is finite-sample biased and these optimal bounds are defined in terms of a particular distribution, and we are using a parameter-preserving transformation to an auxiliary distribution with a lower bound on MSE. 

One side-effect of this is much lower model-misspecification risk.

**Multivariate-t Superefficiency**

To see this, consider the multivariate-t distribution. [Besson & Abromovich (2018)](https://arxiv.org/pdf/1306.6415) extend the Slepian-Bangs formula for the Fisher Information Matrix (FIM) to the broader class of elliptically contoured distributions, and derive the formua for the FIM of the multivariate-t case (equation 28):

$$
F_{ij} = \frac{(d+\nu)n}{d+\nu+1}\text{tr}\{{\mathbf \Sigma}^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_i}{\mathbf \Sigma}^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_j}\} +  \bigg[\frac{(d+\nu)}{d+\nu+1}-1 \bigg]n(\text{tr}(\mathbf \Sigma^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_i})\text{tr}(\mathbf \Sigma^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_j})) 
$$

Where $\nu$ is the degrees of freedom. Note that $\frac{(d+\nu)}{d+\nu+1}<1$, so the first term shrinks the elementwise Fisher information matrix for the Gaussian, and the second term subtracts from it. So in the MSE bound, the Gaussian results in uniformly lower error. Treating this as a matrix, note that we can write $\mathbf F_t$ as a function of $\mathbf F_{\text{Gauss}}$, the Gaussian Fisher information matrix parameterized by the same shape matrix:

$$
\mathbf F_t = \frac{(d+\nu)}{d+\nu+1} \mathbf F_{\text{Gauss}}+n\bigg[\frac{(d+\nu)}{d+\nu+1}-1 \bigg]\mathbf u \mathbf u^\top
$$

Here, $(\mathbf u \mathbf u^\top)_{ij} = u_iu_j = \text{tr}(\mathbf \Sigma^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_i})\text{tr}(\mathbf \Sigma^{-1}\frac{\partial{\mathbf \Sigma}}{\partial \theta_j})$. So $\mathbf F_t$ is just a downscaled version of $\mathbf F_{\text{Gauss}}$ minus a rank-1 PSD matrix. This means that $\mathbf F_t \preceq \mathbf F_{\text{Gauss}}$, which in turn means that the Gaussian CRB matrix achieves a better bound than the t-distribution.

**$\alpha$-stable Superefficiency**

Note: I think we can actually use this same approach, but it's a little tricker due to lack of a closed form density. 


#### Finite-Dimensional Superefficiency 

The superefficiency results above do not require $d \rightarrow \infty$. 

By relying on a Gaussian vector norm for concentration of measure, we can apply the Hanson-Wright inequality to get a probabalistic bound on the efficiency gains relative to the original distribution. 
$$
\begin{aligned}
\mathbb P\bigg(\bigg \| d\hat\tau \frac{XX^\top}{\|X\|^2} - GG^\top\bigg \|_F \geq t \bigg) & = \mathbb P\bigg(\bigg \| d\hat\tau\frac{GG^\top}{\|G\|^2} - GG^\top\bigg \|_F \geq t \bigg) \\ 
&= \mathbb P\bigg(\bigg \| GG^\top \bigg( \frac{d\hat\tau}{\|G\|^2} - 1 \bigg) \bigg \|_F \geq t \bigg) \\
&= \mathbb P\bigg( \| GG^\top \|_F \bigg| \frac{d\bar\sigma^2}{\|G\|^2} - 1 \bigg|  \geq t \bigg) \\
&= \mathbb P\bigg( \| G \|^2 \bigg| \frac{d\hat\tau}{\|G\|^2} - 1 \bigg|  \geq t \bigg) \\
&= \mathbb P( | \|G\|^2 - d \hat\tau |  \geq t ) \\
&= \mathbb P( | \|\Sigma^{1/2}Z\|^2 - d \hat\tau|  \geq t ) \\
&= \mathbb P( | (\Sigma^{1/2}Z)^\top(\Sigma^{1/2}Z) - d \hat\tau |  \geq t ) \\
&= \mathbb P( | Z^\top \Sigma Z - d \hat\tau |  \geq t ) \\
&\leq 2\exp\bigg[-c \min\bigg(\frac{t^2}{\|\Sigma\|_F^2}, \frac{t}{\|\Sigma\|_{\text{op}}}\bigg)\bigg]
\end{aligned}
$$

### Simulation Study