---
title: "Subordinated Covariance Estimator Derivation"
---

We can use the same preliminaries and random variable setup from [this page](corr_variance_derivation.qmd) to get approximations for the expected value and variance of what I'm calling the Subordinated Covariance Estimator, $\hat s$.

Using a second-order Taylor expansion around the means for the expectation, and setting $Y_{ji} = |X_{ji}|^p, Z_j = \sum_{i=1}^N Y_{ji}$, we get "simplified" univariate expansions compared to the correlation-type estimators that approximate the covariance of the subordinated Gaussian vector:

$$
\begin{aligned}
\mathbb E(\hat s) &= \mathbb E \frac{(\frac{1}{N}\sum_{i=1}^N |X_{1i}|^p)^{2/p} + (\frac{1}{N}\sum_{i=1}^N |X_{2i}|^p)^{2/p} -(\frac{1}{N}\sum_{i=1}^N |X_{1i} - X_{2i}|^p)^{2/p}}{C(p,\alpha)^{2/p}} \\
&= N^{-2/p}C(p,\alpha)^{-2/p}\mathbb E\bigg[(\sum_{i=1}^N |X_{1i}|^p)^{2/p}\bigg]+ \mathbb E\bigg[(\sum_{i=1}^N |X_{2i}|^p)^{2/p}\bigg]-\mathbb E\bigg[(\sum_{i=1}^N |X_{1i} - X_{1i}|^p)^{2/p}\bigg] \\ 
&\approx N^{-2/p}C(p,\alpha)^{-2/p} \bigg[ \zeta_1^{2/p}+\zeta_2^{2/p}-\zeta_3^{2/p}-
    \sum_{i=1}^3\frac{(p-2)\zeta_i^{\frac{2}{p}-2}}{p^2}\text{Var}(Z_i) 
 \bigg]\\
 &= N^{-2/p}C(p,\alpha)^{-2/p} \bigg[ \{NC(p,\alpha)\}^{2/p}(\gamma_1^2+\gamma_2^2-\gamma_3^2)- \\
 &\frac{(p-2)\{NC(p,\alpha)\}^{\frac{2}{p}-2}}{p^2} \frac{2^{2p+2}}{N \alpha \sqrt \pi}\bigg\{ \frac{\Gamma(\frac{2p+1}{2})\Gamma(-2p/\alpha)}{\Gamma(-p)} - \frac{\Gamma(\frac{p+1}{2})^2 \Gamma(-p/\alpha)^2 }{\alpha \sqrt\pi\Gamma(-p/2)^2} \bigg\} \bigg(\gamma_1^{2p+\frac{2}{p}-2} + \gamma_2^{2p+\frac{2}{p}-2} - \gamma_3^{2p+\frac{2}{p}-2}\bigg)\bigg] \\
 &= (\gamma_1^2+\gamma_2^2-\gamma_3^2) - \frac{(p-2)}{N^3\{pC(p,\alpha)\}^{2}} \frac{2^{2p+2}}{\alpha \sqrt \pi}\bigg\{ \frac{\Gamma(\frac{2p+1}{2})\Gamma(-2p/\alpha)}{\Gamma(-p)} - \frac{\Gamma(\frac{p+1}{2})^2 \Gamma(-p/\alpha)^2 }{\alpha \sqrt\pi\Gamma(-p/2)^2} \bigg\} \\ &\times\bigg(\gamma_1^{2p+\frac{2}{p}-2} + \gamma_2^{2p+\frac{2}{p}-2} - \gamma_3^{2p+\frac{2}{p}-2}\bigg) \\
 & = \text{Cov}(G_1,G_2) -
 \frac{(p-2)}{N^3\{pC(p,\alpha)\}^{2}} \frac{2^{2p+2}}{\alpha \sqrt \pi}\bigg\{ \frac{\Gamma(\frac{2p+1}{2})\Gamma(-2p/\alpha)}{\Gamma(-p)} - \frac{\Gamma(\frac{p+1}{2})^2 \Gamma(-p/\alpha)^2 }{\alpha \sqrt\pi\Gamma(-p/2)^2} \bigg\} \\ &\times\bigg(\gamma_1^{2p+\frac{2}{p}-2} + \gamma_2^{2p+\frac{2}{p}-2} - \gamma_3^{2p+\frac{2}{p}-2}\bigg)
\end{aligned}
$$

The result above uses the expansion of the rescaled numerator of r from the [progress page](progress.qmd) to move from the stable scale parameters to the covariance of the Gaussian vector.

Moving on to the variance of $\hat s$, with $f(Z_1, Z_1, Z_1) = (C(p, \alpha)N)^{-2/p}[ Z_1^{2/p}+Z_2^{2/p}-Z_3^{2/p}]$:

$$
\begin{aligned}
\text{Var}(\hat s) &\approx  
 \bigg(\frac{\partial f}{\partial Z_1}\bigg|_{\zeta}\bigg)^2\text{Var}(Z_1) +
    \bigg(\frac{\partial f}{\partial Z_2}\bigg|_{\zeta}\bigg)^2\text{Var}(Z_2) +
    \bigg(\frac{\partial f}{\partial Z_3}\bigg|_{\zeta}\bigg)^2\text{Var}(Z_3) +
    2\frac{\partial f}{\partial Z_1}\frac{\partial f}{\partial Z_2}\bigg|_{\zeta}\text{Cov}(Z_1, Z_2) + \\ &
     2\frac{\partial f}{\partial Z_1}\bigg|_{\zeta}\frac{\partial f}{\partial Z_3}\bigg|_{\zeta}\text{Cov}(Z_1, Z_3) +  2\frac{\partial f}{\partial Z_2}\frac{\partial f}{\partial Z_3}\bigg|_{\zeta}\text{Cov}(Z_2, Z_3) \\
&= C(p, \alpha)^{-2}\bigg[\frac{4}{p^2} \bigg\{\gamma_1^{(4p-2)p}\text{Var}(Z_1)+\gamma_2^{(4p-2)p}\text{Var}(Z_2)+\gamma_3^{(4p-2)p}\text{Var}(Z_3)\bigg\}+\\ &\frac{8}{p^2}\bigg\{(\gamma_1^p)^{2/p-1}(\gamma_2^p)^{2/p-1}\text{Cov}(Z_1, Z_2)-(\gamma_1^p)^{2/p-1}(\gamma_3^p)^{2/p-1}\text{Cov}(Z_1, Z_3)-(\gamma_2^p)^{2/p-1}(\gamma_3^p)^{2/p-1}\text{Cov}(Z_2, Z_3)\bigg\}
\bigg]\\
&= N^{-1}C(p, \alpha)^{-2}\bigg[\frac{4}{p^2} \bigg\{\gamma_1^{(4p-2)p}\text{Var}(|X_1|^p)+\gamma_2^{(4p-2)p}\text{Var}(|X_2|^p)+\gamma_3^{(4p-2)p}\text{Var}(|X_3|^p)\bigg\}+\\
 &\frac{8}{p^2}\bigg\{(\gamma_1^p)^{2/p-1}(\gamma_2^p)^{2/p-1}\text{Cov}(|X_1|^p, |X_2|^p)-(\gamma_1^p)^{2/p-1}(\gamma_3^p)^{2/p-1}\text{Cov}(|X_1|^p, |X_3|^p)-\\ &(\gamma_2^p)^{2/p-1}(\gamma_3^p)^{2/p-1}\text{Cov}(|X_2|^p, |X_3|^p)\bigg\}
\bigg]\\
\end{aligned}
$$

There is some additional simplification that happens with the variance terms (they're all identical except for a $\gamma_i^{2p}$), but the expression becomes very complicated very quickly, and doesn't have any obvious simplifications or tricks to make it more interpretable (unlike the expected value). At this point may as well be calculated numerically.

