---
title: "A Superefficiency Proof"
---

This document aims to show a few things: 

1) The Gaussian has the lowest Cramér-Rao lower bound for its scale parameter of any member of the $\alpha$-stable family. This also extends to any scale-Gaussian mixture.

2) We can bound any $d$-dimensional scale-Gaussian mixture's "optimal efficiency gap" (the difference between its MLE efficiency and that of its latent Gaussian) using a scalar multiplication factor $\kappa$ with $\frac{d^2}{d(d+1)} \leq \kappa \leq 1$. This gap depends on the covariance matrix of the latent Gaussian.

I use the notation and conventions introduced in [Besson & Abramovich (2018)](https://arxiv.org/abs/1306.6415), and the standard setup we've been using so far. I'm leaving out some of the verifications of regularity conditions from this page for the sake of space.

## Gaussian CRB vs. Mixtures

The idea that the latent Gaussian has the smallest Cramér-Rao lower bound of all Gaussian mixture scales comes from the missing information principle. 

Call $\mathbf F_{\mathbf X}$ the Fisher Information Matrix (FIM) of the scale parameters w/r/t the random vector X, and call $\mathbf F_{\mathbf G}$ the FIM w/r/t the latent Gaussian vector.

Next, it's clear that if we're interested in the parameterization $\pmb \theta = \text{vech}(\pmb \Sigma)$, the scores of $\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)=\nabla_{\pmb\theta} \log f_{\mathbf G}(\mathbf G,\pmb\theta)$ (e.g. conditioning on W, the rescaling by a constant doesn't change the information we have about the parameter vector). 

Applying Fisher's identity to the score of the stable vector $X$, since $W$ does not depend on the parameter vector $\pmb\theta$, we get: $\nabla_{\pmb\theta} \log f_\mathbf X(\mathbf X|\pmb\theta) = \mathbb E_W[\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)|\mathbf X]$.

Next, plugging this into the law of total variance for the Fisher information of the complete-data score:

$$
\begin{aligned}
\mathbf F_{\mathbf G} &= \text{Cov}(\nabla_{\pmb\theta} \log f_{\mathbf G}(\mathbf G,\pmb\theta)) \\ &= \text{Cov}(\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)) \\
& = \mathbb E_{\mathbf X}[\text{Cov}_{W}(\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)|\mathbf X)] + \text{Cov}_{\mathbf X}[\mathbb E_{W}(\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)|\mathbf X)] \\
& = \mathbb E_{\mathbf X}[\text{Cov}_{W}(\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)|\mathbf X)] + \text{Cov}_{\mathbf X}[\nabla_{\pmb\theta} \log f_\mathbf X(\mathbf X|\pmb\theta) ]\\
&= \mathbb E_{\mathbf X}[\text{Cov}_{W}(\nabla_{\pmb\theta} \log f_{\mathbf X|W}(\mathbf X|W,\pmb\theta)|\mathbf X)] + \mathbf F_{\mathbf X} 
\end{aligned}
$$

So the Fisher information of $\mathbf X$ can be thought of as that of the latent Gaussian vector minus information loss that comes from the uncertainty of W. Since both terms are positive semi-definite matrices, $\mathbf F_{\mathbf G} \succeq  \mathbf F_{\mathbf X} \implies \mathbf F_{\mathbf G}^{-1}\preceq \mathbf F_{\mathbf X}^{-1}$, and the Cramér-Rao lower bound matrix for $\mathbf G$ is the smallest possible of any Gaussian scale mixture in the positive semi-definite ordering.

## Optimal Efficiency Gap Bounds

Besson & Abramovich show that the Slepian-Bangs formula for the Gaussian FIM can be extended to the broader class of elliptically countoured distributions (including Gaussian scale mixtures) based on moments involving the density generator of the distribution in question and moments involving the modular variate $\mathcal Q$.

The stochastic representation $\mathbf X = \sqrt W \mathbf G$ simply decomposes the Gaussian vector into a uniform vector on the unit sphere:

$$
\begin{aligned}
\mathbf X &= \sqrt W \mathbf G \\
& \overset{d}{=} \sqrt W \mathbf C \mathbf Z \\
& = \sqrt W \mathbf C \xi \mathbf u \\
& = \mathcal Q \mathbf C\mathbf u
\end{aligned}
$$

Where $\xi$ is chi-squared with d degrees of freedom, $\mathbf C$ is a $d \times d$ matrix with the property that $\mathbf C\mathbf C^\top = \pmb \Sigma$ (this new name is chosen to make it clear that this matrix is not unique) and $\mathbf u$ is uniform on $\mathbb S^{d-1}$.

Simplifying their equation (22) for our problem for the $i,j$-th entry of the FIM for real-valued EC distributions:

$$
\begin{aligned}
\mathbf {F_{\mathbf X}}_{ij} = 2N\frac{\mathbb E[\mathcal Q^2\phi^2(\mathcal Q)]}{d(d+2)} \text{tr}(\pmb \Sigma^{-1}\pmb \Sigma_i\pmb \Sigma^{-1}\pmb \Sigma_j)+ N\bigg(\frac{\mathbb E[\mathcal Q^2\phi^2(\mathcal Q)]}{d(d+2)}-\frac{1}{4}\bigg)\text{tr}(\pmb \Sigma^{-1}\pmb \Sigma_i)\text{tr}(\pmb \Sigma^{-1}\pmb \Sigma_j)
\end{aligned}
$$

In the above, $\pmb \Sigma_i = \frac{\partial \pmb \Sigma}{\partial \theta_i}$. When $\mathbf X$ is Gaussian, the well-known entry-wise Slepian-Bangs formula for the FIM is: $\mathbf {F_{\mathbf X}}_{ij} = \frac{N}{2}\text{tr}(\pmb \Sigma^{-1}\pmb \Sigma_j\pmb \Sigma^{-1}\pmb \Sigma_k)$. This provides a simple way to rewrite the above in matrix form in terms of the Gaussian FIM, $\mathbf F_{\mathbf G}$:

$$
\begin{aligned}
\mathbf {F_{\mathbf X}} = \frac{4\mathbb E[\mathcal Q^2\phi^2(\mathcal Q)]}{d(d+2)}\mathbf {F_{\mathbf G}} + N\bigg(\frac{\mathbb E[\mathcal Q^2\phi^2(\mathcal Q)]}{d(d+2)}-\frac{1}{4}\bigg) \nabla_{\pmb\theta} \log(\det(\pmb \Sigma))\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))^\top
\end{aligned}
$$

Where $(\mathbf s\mathbf s^\top)_{ij}=s_i s_j = \text{tr}(\pmb \Sigma^{-1}\frac{\partial \pmb \Sigma}{\partial \theta_i})\text{tr}(\pmb \Sigma^{-1}\frac{\partial \pmb \Sigma}{\partial \theta_j})$. In other words, this term is the outer product of a vector of these derivative/inverse traces.

Since the prefactor on the second term is always negative, this says any elliptically countoured scale-variance mixture has a FIM that can be written as the sum of a downscaled version of the corresponding Gaussian FIM minus a rank-one positive semi-definite matrix. 

For any elliptically-contoured distribution satisfying the regularity conditions in Besson & Abramovich, $\mathbb E[\mathcal Q\phi(\mathcal Q)]=-d/2$. So Jensen's inequality gives $\mathbb E[\mathcal Q^2\phi^2(\mathcal Q)]\geq d^2/4$. Since part 1 showed that the Gaussian has the largest FIM of any Gaussian scale mixture, that means $d^2/4 \leq \mathbb E[\mathcal Q^2\phi^2(\mathcal Q)] \leq d(d+2)/4$, and so if we call the prefactor on $\mathbf {F_{\mathbf G}}$ $\kappa$, we get $\kappa$ with $\frac{d^2}{d(d+2)} \leq \kappa \leq 1$.

$$
\begin{aligned}
\mathbf {F_{\mathbf X}} = \kappa\mathbf {F_{\mathbf G}} - \frac{N}{4}(1-\kappa) \nabla_{\pmb\theta} \log(\det(\pmb \Sigma))\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))^\top\\
\end{aligned}
$$

This scaling term gives us the ability to quantify the "optimal efficiency gap" we gain in the high-dimensional limit by transforming to an approximately Gaussian distribution rather than the original MLE. This benefit depends on the estimation dimension rather than the ambient dimension. This is an example of how the projective estimator takes advantage of additional information from additional dimensions for estimation in the higher ambient-dimensional setting.

The advantage that we see from the the downscaling of $\kappa$ itself is modest when the dimensions are high, but when the eigenvalues of $\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))^\top$ are large, we see potentially significant performance improvements. 

More realistically, looking at the impact of the $s\mathbf s^\top$ term...

Since $\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))\nabla_{\pmb\theta} \log(\det(\pmb \Sigma))^\top$ is a rank-1 psd matrix, its eigenvalue is just the trace of this matrix: $\lambda_s = \sum_i (\text{tr}(\pmb\Sigma^{-1}\frac{\partial \pmb \Sigma}{\partial \theta_i})^2)$. 


-----------------

"The information loss due to the heavy-tailed, non-Gaussian nature of the data is not uniform. It is an anisotropic penalty that is specifically directed along the gradient of the log-volume.

In other words, the confounding effect of the random scaling W most severely degrades your ability to make inferences about the parameters that have the greatest impact on the overall volume of the uncertainty ellipsoid"

**CHEAP FIM calculation for alpha stable distributions** Make d large enough that d^2 is close enough to d(d+1). Then use the above formualtion using the gradient of the log determinant of Sigma.